[build]
publish = "dist"


[[redirects]]    
    from = "*"
    to = "https://cornishlocals.com/about/:splat"
    status = 200
    force = true
  ## more info on configuring this file: https://www.netlify.com/docs/netlify-toml-reference/
